import { Component } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';
import { provideNativeDateAdapter } from '@angular/material/core';
import {
  MAT_DATE_RANGE_SELECTION_STRATEGY,
  MatDatepickerModule,
} from '@angular/material/datepicker';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { ToastrModule, ToastrService } from 'ngx-toastr';
import { AppBreadcrumbComponent } from 'src/app/layouts/full/shared/breadcrumb/breadcrumb.component';
import { FiveDayRangeSelectionStrategy } from 'src/app/pages/forms/form-elements';
import { ClientHttpService } from '../services/client-http.service';
import { catchError, filter, map, switchMap } from 'rxjs';
import { Client } from '../models/client';
import { MatSelectModule } from '@angular/material/select';
import { MatCardModule } from '@angular/material/card';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-client-edit',
  imports: [
    AppBreadcrumbComponent,
    MatFormFieldModule,
    MatInputModule,
    MatDatepickerModule,
    ReactiveFormsModule,
    ToastrModule,
    RouterModule,
    MatSelectModule,
    MatButtonModule,
    MatCardModule,
  ],
  providers: [
    ClientHttpService,
    ToastrService,
    provideNativeDateAdapter(),
    {
      provide: MAT_DATE_RANGE_SELECTION_STRATEGY,
      useClass: FiveDayRangeSelectionStrategy,
    },
  ],
  templateUrl: './client-edit.component.html',
  styleUrl: './client-edit.component.scss',
})
export class ClientEditComponent {
  clientForm: FormGroup;
  clientId: string;
  showPartner: boolean = false;

  constructor(
    private fb: FormBuilder,
    private clientHttpService: ClientHttpService,
    private router: Router,
    private toastr: ToastrService,
    private activatedRoute: ActivatedRoute
  ) {
    this.clientForm = this.fb.group({
      name: ['', Validators.required],
      dob: ['', Validators.required],
      gender: [''],
      country: [''],
      currency: [''],
      email: ['', [Validators.email]],
      phone: [''],
      notes: [''],
      partner: this.fb.group({
        name: [''],
        dob: [''],
        gender: [''],
        country: [''],
        currency: [''],
        email: ['', [Validators.email]],
        phone: [''],
      }),
    });

    this.getClient();
    this.togglePartnerSection(false); // Ensure partner section validations are off initially
  }

  getClient() {
    this.activatedRoute.params.pipe(
      switchMap((params) => {
        this.clientId = params['id']
        return this.clientHttpService.getClient(this.clientId);
      }),
      map((res) => {
        this.clientForm.controls['dob'].patchValue(res.clientDetails.birthDate);
        this.clientForm.controls['email'].patchValue(res.clientDetails.email);
        this.clientForm.controls['gender'].patchValue(res.clientDetails.gender);
        this.clientForm.controls['country'].patchValue(res.clientDetails.country);
        this.clientForm.controls['name'].patchValue(res.clientDetails.name);
        this.clientForm.controls['phone'].patchValue(res.clientDetails.phone);
        this.clientForm.controls['currency'].patchValue(res.clientDetails.preferredCurrency);
        this.clientForm.controls['notes'].patchValue(res.notes);
        if(res.partnerDetail?.name) {
          this.togglePartnerSection(true);
          var partnerFormGroup = this.clientForm.get('partner') as FormGroup
          partnerFormGroup.controls['dob'].patchValue(res.partnerDetail.birthDate);
          partnerFormGroup.controls['email'].patchValue(res.partnerDetail.email);
          partnerFormGroup.controls['gender'].patchValue(res.partnerDetail.gender);
          partnerFormGroup.controls['country'].patchValue(res.partnerDetail.country);
          partnerFormGroup.controls['name'].patchValue(res.partnerDetail.name);
          partnerFormGroup.controls['phone'].patchValue(res.partnerDetail.phone);
          partnerFormGroup.controls['currency'].patchValue(res.partnerDetail.preferredCurrency);
        }

        this.clientForm.updateValueAndValidity();
        
      })
    ).subscribe()
  }

  togglePartnerSection(visible: boolean) {
    this.showPartner = visible;
    const partnerGroup = this.clientForm.get('partner') as FormGroup;

    if (visible) {
      partnerGroup.get('name')?.setValidators(Validators.required);
      partnerGroup.get('dob')?.setValidators(Validators.required);
    } else {
      partnerGroup.reset();
      Object.keys(partnerGroup.controls).forEach((key) => {
        partnerGroup.get(key)?.clearValidators();
        partnerGroup.get(key)?.updateValueAndValidity();
      });
    }
  }

  onSubmit() {
    if (this.clientForm.valid) {
      const partnerGroup = this.clientForm.get('partner') as FormGroup;
      var client: Client = {
        id: this.clientId,
        clientDetails: {
          birthDate: this.clientForm.controls['dob'].value,
          email: this.clientForm.controls['email'].value,
          gender: this.clientForm.controls['gender'].value,
          country: this.clientForm.controls['country'].value,
          name: this.clientForm.controls['name'].value,
          phone: this.clientForm.controls['phone'].value,
          preferredCurrency: this.clientForm.controls['currency'].value,
        },
        partnerDetail: this.showPartner ? {
          birthDate: partnerGroup.controls['dob']?.value,
          email: partnerGroup.controls['email']?.value,
          gender: partnerGroup.controls['gender']?.value,
          country: partnerGroup.controls['country']?.value,
          name: partnerGroup.controls['name']?.value,
          phone: partnerGroup.controls['phone']?.value,
          preferredCurrency:
            partnerGroup.controls['currency']?.value,
        } : null,
        financialAdvisor: {
          advisorId: '678c93f32be72db4b9631be1',
          advisorName: 'Matteo',
        },
        lastUpdated: new Date(),
        notes: this.clientForm.controls['notes'].value,
      };
      this.clientHttpService
        .updateClient(client)
        .pipe(
          filter((res) => !!res),
          map((res) => {
            this.router.navigate(['/clients']);
            this.toastr.success('Client updated successfully', 'Success!');
          }),
          catchError((err) => {
            console.error(err);
            this.toastr.error('An error occured while saving client', 'Error!');
            throw err;
          })
        )
        .subscribe();
      console.log('Form Data:', this.clientForm.value);
      // Submit form data to the API or service
    } else {
      console.error('Form is invalid');
    }
  }


  allCountries = [
    {
      countryName: 'Aruba',
      countryCode: 'AW',
      phoneFormat: '',
      currencySymbol: 'AWG',
      currencyName: '',
    },
    {
      countryName: 'Afghanistan',
      countryCode: 'AF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Angola',
      countryCode: 'AO',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Anguilla',
      countryCode: 'AI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: '\u00c5land Islands',
      countryCode: 'AX',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Albania',
      countryCode: 'AL',
      phoneFormat: '',
      currencySymbol: 'ALL',
      currencyName: '',
    },
    {
      countryName: 'Andorra',
      countryCode: 'AD',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'United Arab Emirates',
      countryCode: 'AE',
      phoneFormat: '',
      currencySymbol: 'AED',
      currencyName: 'Dirham',
    },
    {
      countryName: 'Argentina',
      countryCode: 'AR',
      phoneFormat: '',
      currencySymbol: 'ARS',
      currencyName: '',
    },
    {
      countryName: 'Armenia',
      countryCode: 'AM',
      phoneFormat: '',
      currencySymbol: 'AMD',
      currencyName: '',
    },
    {
      countryName: 'American Samoa',
      countryCode: 'AS',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Antarctica',
      countryCode: 'AQ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'French Southern Territories',
      countryCode: 'TF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Antigua and Barbuda',
      countryCode: 'AG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Australia',
      countryCode: 'AU',
      phoneFormat: '',
      currencySymbol: 'AUD',
      currencyName: 'Dollar',
    },
    {
      countryName: 'Austria',
      countryCode: 'AT',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Azerbaijan',
      countryCode: 'AZ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Burundi',
      countryCode: 'BI',
      phoneFormat: '',
      currencySymbol: 'BIF',
      currencyName: '',
    },
    {
      countryName: 'Belgium',
      countryCode: 'BE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Benin',
      countryCode: 'BJ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Bonaire, Sint Eustatius and Saba',
      countryCode: 'BQ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Burkina Faso',
      countryCode: 'BF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Bangladesh',
      countryCode: 'BD',
      phoneFormat: '',
      currencySymbol: 'BDT',
      currencyName: '',
    },
    {
      countryName: 'Bulgaria',
      countryCode: 'BG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Bahrain',
      countryCode: 'BH',
      phoneFormat: '',
      currencySymbol: 'BHD',
      currencyName: '',
    },
    {
      countryName: 'Bahamas',
      countryCode: 'BS',
      phoneFormat: '',
      currencySymbol: 'BSD',
      currencyName: '',
    },
    {
      countryName: 'Bosnia and Herzegovina',
      countryCode: 'BA',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Saint Barth\u00e9lemy',
      countryCode: 'BL',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Belarus',
      countryCode: 'BY',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Belize',
      countryCode: 'BZ',
      phoneFormat: '',
      currencySymbol: 'BZD',
      currencyName: '',
    },
    {
      countryName: 'Bermuda',
      countryCode: 'BM',
      phoneFormat: '',
      currencySymbol: 'BMD',
      currencyName: '',
    },
    {
      countryName: 'Bolivia, Plurinational State of',
      countryCode: 'BO',
      phoneFormat: '',
      currencySymbol: 'BOB',
      currencyName: '',
    },
    {
      countryName: 'Brazil',
      countryCode: 'BR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Barbados',
      countryCode: 'BB',
      phoneFormat: '',
      currencySymbol: 'BBD',
      currencyName: '',
    },
    {
      countryName: 'Brunei Darussalam',
      countryCode: 'BN',
      phoneFormat: '',
      currencySymbol: 'BND',
      currencyName: '',
    },
    {
      countryName: 'Bhutan',
      countryCode: 'BT',
      phoneFormat: '',
      currencySymbol: 'BTN',
      currencyName: '',
    },
    {
      countryName: 'Bouvet Island',
      countryCode: 'BV',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Botswana',
      countryCode: 'BW',
      phoneFormat: '',
      currencySymbol: 'BWP',
      currencyName: '',
    },
    {
      countryName: 'Central African Republic',
      countryCode: 'CF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Canada',
      countryCode: 'CA',
      phoneFormat: '',
      currencySymbol: 'CAD',
      currencyName: 'Dollar',
    },
    {
      countryName: 'Cocos (Keeling) Islands',
      countryCode: 'CC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Switzerland',
      countryCode: 'CH',
      phoneFormat: '',
      currencySymbol: 'CHF',
      currencyName: '',
    },
    {
      countryName: 'Chile',
      countryCode: 'CL',
      phoneFormat: '',
      currencySymbol: 'CLP',
      currencyName: '',
    },
    {
      countryName: 'China',
      countryCode: 'CN',
      phoneFormat: '',
      currencySymbol: 'CNY',
      currencyName: '',
    },
    {
      countryName: "C\u00f4te d'Ivoire",
      countryCode: 'CI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Cameroon',
      countryCode: 'CM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Congo, The Democratic Republic of the',
      countryCode: 'CD',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Congo',
      countryCode: 'CG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Cook Islands',
      countryCode: 'CK',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Colombia',
      countryCode: 'CO',
      phoneFormat: '',
      currencySymbol: 'COP',
      currencyName: '',
    },
    {
      countryName: 'Comoros',
      countryCode: 'KM',
      phoneFormat: '',
      currencySymbol: 'KMF',
      currencyName: '',
    },
    {
      countryName: 'Cabo Verde',
      countryCode: 'CV',
      phoneFormat: '',
      currencySymbol: 'CVE',
      currencyName: '',
    },
    {
      countryName: 'Costa Rica',
      countryCode: 'CR',
      phoneFormat: '',
      currencySymbol: 'CRC',
      currencyName: '',
    },
    {
      countryName: 'Cuba',
      countryCode: 'CU',
      phoneFormat: '',
      currencySymbol: 'CUP',
      currencyName: '',
    },
    {
      countryName: 'Cura\u00e7ao',
      countryCode: 'CW',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Christmas Island',
      countryCode: 'CX',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Cayman Islands',
      countryCode: 'KY',
      phoneFormat: '',
      currencySymbol: 'KYD',
      currencyName: '',
    },
    {
      countryName: 'Cyprus',
      countryCode: 'CY',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Czechia',
      countryCode: 'CZ',
      phoneFormat: '',
      currencySymbol: 'CZK',
      currencyName: '',
    },
    {
      countryName: 'Germany',
      countryCode: 'DE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Djibouti',
      countryCode: 'DJ',
      phoneFormat: '',
      currencySymbol: 'DJF',
      currencyName: '',
    },
    {
      countryName: 'Dominica',
      countryCode: 'DM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Denmark',
      countryCode: 'DK',
      phoneFormat: '',
      currencySymbol: 'DKK',
      currencyName: '',
    },
    {
      countryName: 'Dominican Republic',
      countryCode: 'DO',
      phoneFormat: '',
      currencySymbol: 'DOP',
      currencyName: '',
    },
    {
      countryName: 'Algeria',
      countryCode: 'DZ',
      phoneFormat: '',
      currencySymbol: 'DZD',
      currencyName: '',
    },
    {
      countryName: 'Ecuador',
      countryCode: 'EC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Egypt',
      countryCode: 'EG',
      phoneFormat: '',
      currencySymbol: 'EGP',
      currencyName: '',
    },
    {
      countryName: 'Eritrea',
      countryCode: 'ER',
      phoneFormat: '',
      currencySymbol: 'ERN',
      currencyName: '',
    },
    {
      countryName: 'Western Sahara',
      countryCode: 'EH',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Spain',
      countryCode: 'ES',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Estonia',
      countryCode: 'EE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Ethiopia',
      countryCode: 'ET',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Finland',
      countryCode: 'FI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Fiji',
      countryCode: 'FJ',
      phoneFormat: '',
      currencySymbol: 'FJD',
      currencyName: '',
    },
    {
      countryName: 'Falkland Islands (Malvinas)',
      countryCode: 'FK',
      phoneFormat: '',
      currencySymbol: 'FKP',
      currencyName: '',
    },
    {
      countryName: 'France',
      countryCode: 'FR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Faroe Islands',
      countryCode: 'FO',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Micronesia, Federated States of',
      countryCode: 'FM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Gabon',
      countryCode: 'GA',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'United Kingdom',
      countryCode: 'GB',
      phoneFormat: '',
      currencySymbol: 'GBP',
      currencyName: 'Pound Sterling',
    },
    {
      countryName: 'Georgia',
      countryCode: 'GE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Guernsey',
      countryCode: 'GG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Ghana',
      countryCode: 'GH',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Gibraltar',
      countryCode: 'GI',
      phoneFormat: '',
      currencySymbol: 'GIP',
      currencyName: '',
    },
    {
      countryName: 'Guinea',
      countryCode: 'GN',
      phoneFormat: '',
      currencySymbol: 'GNF',
      currencyName: '',
    },
    {
      countryName: 'Guadeloupe',
      countryCode: 'GP',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Gambia',
      countryCode: 'GM',
      phoneFormat: '',
      currencySymbol: 'GMD',
      currencyName: '',
    },
    {
      countryName: 'Guinea-Bissau',
      countryCode: 'GW',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Equatorial Guinea',
      countryCode: 'GQ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Greece',
      countryCode: 'GR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Grenada',
      countryCode: 'GD',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Greenland',
      countryCode: 'GL',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Guatemala',
      countryCode: 'GT',
      phoneFormat: '',
      currencySymbol: 'GTQ',
      currencyName: '',
    },
    {
      countryName: 'French Guiana',
      countryCode: 'GF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Guam',
      countryCode: 'GU',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Guyana',
      countryCode: 'GY',
      phoneFormat: '',
      currencySymbol: 'GYD',
      currencyName: '',
    },
    {
      countryName: 'Hong Kong',
      countryCode: 'HK',
      phoneFormat: '',
      currencySymbol: 'HKD',
      currencyName: '',
    },
    {
      countryName: 'Heard Island and McDonald Islands',
      countryCode: 'HM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Honduras',
      countryCode: 'HN',
      phoneFormat: '',
      currencySymbol: 'HNL',
      currencyName: '',
    },
    {
      countryName: 'Croatia',
      countryCode: 'HR',
      phoneFormat: '',
      currencySymbol: 'HRK',
      currencyName: '',
    },
    {
      countryName: 'Haiti',
      countryCode: 'HT',
      phoneFormat: '',
      currencySymbol: 'HTG',
      currencyName: '',
    },
    {
      countryName: 'Hungary',
      countryCode: 'HU',
      phoneFormat: '',
      currencySymbol: 'HUF',
      currencyName: '',
    },
    {
      countryName: 'Indonesia',
      countryCode: 'ID',
      phoneFormat: '',
      currencySymbol: 'IDR',
      currencyName: '',
    },
    {
      countryName: 'Isle of Man',
      countryCode: 'IM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'India',
      countryCode: 'IN',
      phoneFormat: '',
      currencySymbol: 'INR',
      currencyName: 'Rupee',
    },
    {
      countryName: 'British Indian Ocean Territory',
      countryCode: 'IO',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Ireland',
      countryCode: 'IE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Iran, Islamic Republic of',
      countryCode: 'IR',
      phoneFormat: '',
      currencySymbol: 'IRR',
      currencyName: '',
    },
    {
      countryName: 'Iraq',
      countryCode: 'IQ',
      phoneFormat: '',
      currencySymbol: 'IQD',
      currencyName: '',
    },
    {
      countryName: 'Iceland',
      countryCode: 'IS',
      phoneFormat: '',
      currencySymbol: 'ISK',
      currencyName: '',
    },
    {
      countryName: 'Israel',
      countryCode: 'IL',
      phoneFormat: '',
      currencySymbol: 'ILS',
      currencyName: '',
    },
    {
      countryName: 'Italy',
      countryCode: 'IT',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Jamaica',
      countryCode: 'JM',
      phoneFormat: '',
      currencySymbol: 'JMD',
      currencyName: '',
    },
    {
      countryName: 'Jersey',
      countryCode: 'JE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Jordan',
      countryCode: 'JO',
      phoneFormat: '',
      currencySymbol: 'JOD',
      currencyName: '',
    },
    {
      countryName: 'Japan',
      countryCode: 'JP',
      phoneFormat: '',
      currencySymbol: 'JPY',
      currencyName: 'Yen',
    },
    {
      countryName: 'Kazakhstan',
      countryCode: 'KZ',
      phoneFormat: '',
      currencySymbol: 'KZT',
      currencyName: '',
    },
    {
      countryName: 'Kenya',
      countryCode: 'KE',
      phoneFormat: '',
      currencySymbol: 'KES',
      currencyName: '',
    },
    {
      countryName: 'Kyrgyzstan',
      countryCode: 'KG',
      phoneFormat: '',
      currencySymbol: 'KGS',
      currencyName: '',
    },
    {
      countryName: 'Cambodia',
      countryCode: 'KH',
      phoneFormat: '',
      currencySymbol: 'KHR',
      currencyName: '',
    },
    {
      countryName: 'Kiribati',
      countryCode: 'KI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Saint Kitts and Nevis',
      countryCode: 'KN',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Korea, Republic of',
      countryCode: 'KR',
      phoneFormat: '',
      currencySymbol: 'KRW',
      currencyName: '',
    },
    {
      countryName: 'Kuwait',
      countryCode: 'KW',
      phoneFormat: '',
      currencySymbol: 'KWD',
      currencyName: '',
    },
    {
      countryName: "Lao People's Democratic Republic",
      countryCode: 'LA',
      phoneFormat: '',
      currencySymbol: 'LAK',
      currencyName: '',
    },
    {
      countryName: 'Lebanon',
      countryCode: 'LB',
      phoneFormat: '',
      currencySymbol: 'LBP',
      currencyName: '',
    },
    {
      countryName: 'Liberia',
      countryCode: 'LR',
      phoneFormat: '',
      currencySymbol: 'LRD',
      currencyName: '',
    },
    {
      countryName: 'Libya',
      countryCode: 'LY',
      phoneFormat: '',
      currencySymbol: 'LYD',
      currencyName: '',
    },
    {
      countryName: 'Saint Lucia',
      countryCode: 'LC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Liechtenstein',
      countryCode: 'LI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Sri Lanka',
      countryCode: 'LK',
      phoneFormat: '',
      currencySymbol: 'LKR',
      currencyName: '',
    },
    {
      countryName: 'Lesotho',
      countryCode: 'LS',
      phoneFormat: '',
      currencySymbol: 'LSL',
      currencyName: '',
    },
    {
      countryName: 'Lithuania',
      countryCode: 'LT',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Luxembourg',
      countryCode: 'LU',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Latvia',
      countryCode: 'LV',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Macao',
      countryCode: 'MO',
      phoneFormat: '',
      currencySymbol: 'MOP',
      currencyName: '',
    },
    {
      countryName: 'Saint Martin (French part)',
      countryCode: 'MF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Morocco',
      countryCode: 'MA',
      phoneFormat: '',
      currencySymbol: 'MAD',
      currencyName: '',
    },
    {
      countryName: 'Monaco',
      countryCode: 'MC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Moldova, Republic of',
      countryCode: 'MD',
      phoneFormat: '',
      currencySymbol: 'MDL',
      currencyName: '',
    },
    {
      countryName: 'Madagascar',
      countryCode: 'MG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Maldives',
      countryCode: 'MV',
      phoneFormat: '',
      currencySymbol: 'MVR',
      currencyName: '',
    },
    {
      countryName: 'Mexico',
      countryCode: 'MX',
      phoneFormat: '',
      currencySymbol: 'MXN',
      currencyName: '',
    },
    {
      countryName: 'Marshall Islands',
      countryCode: 'MH',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'North Macedonia',
      countryCode: 'MK',
      phoneFormat: '',
      currencySymbol: 'MKD',
      currencyName: '',
    },
    {
      countryName: 'Mali',
      countryCode: 'ML',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Malta',
      countryCode: 'MT',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Myanmar',
      countryCode: 'MM',
      phoneFormat: '',
      currencySymbol: 'MMK',
      currencyName: '',
    },
    {
      countryName: 'Montenegro',
      countryCode: 'ME',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Mongolia',
      countryCode: 'MN',
      phoneFormat: '',
      currencySymbol: 'MNT',
      currencyName: '',
    },
    {
      countryName: 'Northern Mariana Islands',
      countryCode: 'MP',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Mozambique',
      countryCode: 'MZ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Mauritania',
      countryCode: 'MR',
      phoneFormat: '',
      currencySymbol: 'MRO',
      currencyName: '',
    },
    {
      countryName: 'Montserrat',
      countryCode: 'MS',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Martinique',
      countryCode: 'MQ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Mauritius',
      countryCode: 'MU',
      phoneFormat: '',
      currencySymbol: 'MUR',
      currencyName: '',
    },
    {
      countryName: 'Malawi',
      countryCode: 'MW',
      phoneFormat: '',
      currencySymbol: 'MWK',
      currencyName: '',
    },
    {
      countryName: 'Malaysia',
      countryCode: 'MY',
      phoneFormat: '',
      currencySymbol: 'MYR',
      currencyName: '',
    },
    {
      countryName: 'Mayotte',
      countryCode: 'YT',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Namibia',
      countryCode: 'NA',
      phoneFormat: '',
      currencySymbol: 'NAD',
      currencyName: '',
    },
    {
      countryName: 'New Caledonia',
      countryCode: 'NC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Niger',
      countryCode: 'NE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Norfolk Island',
      countryCode: 'NF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Nigeria',
      countryCode: 'NG',
      phoneFormat: '',
      currencySymbol: 'NGN',
      currencyName: '',
    },
    {
      countryName: 'Nicaragua',
      countryCode: 'NI',
      phoneFormat: '',
      currencySymbol: 'NIO',
      currencyName: '',
    },
    {
      countryName: 'Niue',
      countryCode: 'NU',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Netherlands',
      countryCode: 'NL',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Norway',
      countryCode: 'NO',
      phoneFormat: '',
      currencySymbol: 'NOK',
      currencyName: '',
    },
    {
      countryName: 'Nepal',
      countryCode: 'NP',
      phoneFormat: '',
      currencySymbol: 'NPR',
      currencyName: '',
    },
    {
      countryName: 'Nauru',
      countryCode: 'NR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'New Zealand',
      countryCode: 'NZ',
      phoneFormat: '',
      currencySymbol: 'NZD',
      currencyName: '',
    },
    {
      countryName: 'Oman',
      countryCode: 'OM',
      phoneFormat: '',
      currencySymbol: 'OMR',
      currencyName: '',
    },
    {
      countryName: 'Pakistan',
      countryCode: 'PK',
      phoneFormat: '',
      currencySymbol: 'PKR',
      currencyName: '',
    },
    {
      countryName: 'Panama',
      countryCode: 'PA',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Pitcairn',
      countryCode: 'PN',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Peru',
      countryCode: 'PE',
      phoneFormat: '',
      currencySymbol: 'PEN',
      currencyName: '',
    },
    {
      countryName: 'Philippines',
      countryCode: 'PH',
      phoneFormat: '',
      currencySymbol: 'PHP',
      currencyName: '',
    },
    {
      countryName: 'Palau',
      countryCode: 'PW',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Papua New Guinea',
      countryCode: 'PG',
      phoneFormat: '',
      currencySymbol: 'PGK',
      currencyName: '',
    },
    {
      countryName: 'Poland',
      countryCode: 'PL',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Puerto Rico',
      countryCode: 'PR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: "Korea, Democratic People's Republic of",
      countryCode: 'KP',
      phoneFormat: '',
      currencySymbol: 'KPW',
      currencyName: '',
    },
    {
      countryName: 'Portugal',
      countryCode: 'PT',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Paraguay',
      countryCode: 'PY',
      phoneFormat: '',
      currencySymbol: 'PYG',
      currencyName: '',
    },
    {
      countryName: 'Palestine, State of',
      countryCode: 'PS',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'French Polynesia',
      countryCode: 'PF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Qatar',
      countryCode: 'QA',
      phoneFormat: '',
      currencySymbol: 'QAR',
      currencyName: '',
    },
    {
      countryName: 'R\u00e9union',
      countryCode: 'RE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Romania',
      countryCode: 'RO',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Russian Federation',
      countryCode: 'RU',
      phoneFormat: '',
      currencySymbol: 'RUB',
      currencyName: '',
    },
    {
      countryName: 'Rwanda',
      countryCode: 'RW',
      phoneFormat: '',
      currencySymbol: 'RWF',
      currencyName: '',
    },
    {
      countryName: 'Saudi Arabia',
      countryCode: 'SA',
      phoneFormat: '',
      currencySymbol: 'SAR',
      currencyName: 'Riyal',
    },
    {
      countryName: 'Sudan',
      countryCode: 'SD',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Senegal',
      countryCode: 'SN',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Singapore',
      countryCode: 'SG',
      phoneFormat: '',
      currencySymbol: 'SGD',
      currencyName: '',
    },
    {
      countryName: 'South Georgia and the South Sandwich Islands',
      countryCode: 'GS',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Saint Helena, Ascension and Tristan da Cunha',
      countryCode: 'SH',
      phoneFormat: '',
      currencySymbol: 'SHP',
      currencyName: '',
    },
    {
      countryName: 'Svalbard and Jan Mayen',
      countryCode: 'SJ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Solomon Islands',
      countryCode: 'SB',
      phoneFormat: '',
      currencySymbol: 'SBD',
      currencyName: '',
    },
    {
      countryName: 'Sierra Leone',
      countryCode: 'SL',
      phoneFormat: '',
      currencySymbol: 'SLL',
      currencyName: '',
    },
    {
      countryName: 'El Salvador',
      countryCode: 'SV',
      phoneFormat: '',
      currencySymbol: 'SVC',
      currencyName: '',
    },
    {
      countryName: 'San Marino',
      countryCode: 'SM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Somalia',
      countryCode: 'SO',
      phoneFormat: '',
      currencySymbol: 'SOS',
      currencyName: '',
    },
    {
      countryName: 'Saint Pierre and Miquelon',
      countryCode: 'PM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Serbia',
      countryCode: 'RS',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'South Sudan',
      countryCode: 'SS',
      phoneFormat: '',
      currencySymbol: 'SSP',
      currencyName: '',
    },
    {
      countryName: 'Sao Tome and Principe',
      countryCode: 'ST',
      phoneFormat: '',
      currencySymbol: 'STD',
      currencyName: '',
    },
    {
      countryName: 'Suriname',
      countryCode: 'SR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Slovakia',
      countryCode: 'SK',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Slovenia',
      countryCode: 'SI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Sweden',
      countryCode: 'SE',
      phoneFormat: '',
      currencySymbol: 'SEK',
      currencyName: '',
    },
    {
      countryName: 'Eswatini',
      countryCode: 'SZ',
      phoneFormat: '',
      currencySymbol: 'SZL',
      currencyName: '',
    },
    {
      countryName: 'Sint Maarten (Dutch part)',
      countryCode: 'SX',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Seychelles',
      countryCode: 'SC',
      phoneFormat: '',
      currencySymbol: 'SCR',
      currencyName: '',
    },
    {
      countryName: 'Syrian Arab Republic',
      countryCode: 'SY',
      phoneFormat: '',
      currencySymbol: 'SYP',
      currencyName: '',
    },
    {
      countryName: 'Turks and Caicos Islands',
      countryCode: 'TC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Chad',
      countryCode: 'TD',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Togo',
      countryCode: 'TG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Thailand',
      countryCode: 'TH',
      phoneFormat: '',
      currencySymbol: 'THB',
      currencyName: '',
    },
    {
      countryName: 'Tajikistan',
      countryCode: 'TJ',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Tokelau',
      countryCode: 'TK',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Turkmenistan',
      countryCode: 'TM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Timor-Leste',
      countryCode: 'TL',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Tonga',
      countryCode: 'TO',
      phoneFormat: '',
      currencySymbol: 'TOP',
      currencyName: '',
    },
    {
      countryName: 'Trinidad and Tobago',
      countryCode: 'TT',
      phoneFormat: '',
      currencySymbol: 'TTD',
      currencyName: '',
    },
    {
      countryName: 'Tunisia',
      countryCode: 'TN',
      phoneFormat: '',
      currencySymbol: 'TND',
      currencyName: '',
    },
    {
      countryName: 'Turkey',
      countryCode: 'TR',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Tuvalu',
      countryCode: 'TV',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Taiwan, Province of China',
      countryCode: 'TW',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Tanzania, United Republic of',
      countryCode: 'TZ',
      phoneFormat: '',
      currencySymbol: 'TZS',
      currencyName: '',
    },
    {
      countryName: 'Uganda',
      countryCode: 'UG',
      phoneFormat: '',
      currencySymbol: 'UGX',
      currencyName: '',
    },
    {
      countryName: 'Ukraine',
      countryCode: 'UA',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'United States Minor Outlying Islands',
      countryCode: 'UM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Uruguay',
      countryCode: 'UY',
      phoneFormat: '',
      currencySymbol: 'UYU',
      currencyName: '',
    },
    {
      countryName: 'United States',
      countryCode: 'US',
      phoneFormat: '',
      currencySymbol: 'USD',
      currencyName: 'Dollar',
    },
    {
      countryName: 'Uzbekistan',
      countryCode: 'UZ',
      phoneFormat: '',
      currencySymbol: 'UZS',
      currencyName: '',
    },
    {
      countryName: 'Holy See (Vatican City State)',
      countryCode: 'VA',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Saint Vincent and the Grenadines',
      countryCode: 'VC',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Venezuela, Bolivarian Republic of',
      countryCode: 'VE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Virgin Islands, British',
      countryCode: 'VG',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Virgin Islands, U.S.',
      countryCode: 'VI',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Viet Nam',
      countryCode: 'VN',
      phoneFormat: '',
      currencySymbol: 'VND',
      currencyName: '',
    },
    {
      countryName: 'Vanuatu',
      countryCode: 'VU',
      phoneFormat: '',
      currencySymbol: 'VUV',
      currencyName: '',
    },
    {
      countryName: 'Wallis and Futuna',
      countryCode: 'WF',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Samoa',
      countryCode: 'WS',
      phoneFormat: '',
      currencySymbol: 'WST',
      currencyName: '',
    },
    {
      countryName: 'Yemen',
      countryCode: 'YE',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'South Africa',
      countryCode: 'ZA',
      phoneFormat: '',
      currencySymbol: 'ZAR',
      currencyName: 'Rand',
    },
    {
      countryName: 'Zambia',
      countryCode: 'ZM',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
    {
      countryName: 'Zimbabwe',
      countryCode: 'ZW',
      phoneFormat: '',
      currencySymbol: '',
      currencyName: '',
    },
  ];
}
